// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1DaxOYHQj37_7QOlwlXm24itdjcNWU4',
    appId: '1:1043017147554:web:ffe5915390497c8ac063fb',
    messagingSenderId: '1043017147554',
    projectId: 'safeti-71954',
    authDomain: 'safeti-71954.firebaseapp.com',
    storageBucket: 'safeti-71954.appspot.com',
    measurementId: 'G-S3JLZECFLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DWCXaqP0oXhF_APOsbQKyvZdHi1fUdg',
    appId: '1:1043017147554:android:67a035551b0f70b7c063fb',
    messagingSenderId: '1043017147554',
    projectId: 'safeti-71954',
    storageBucket: 'safeti-71954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1AQU4i1d228jyQmPrgJTDYzL514YmOc',
    appId: '1:1043017147554:ios:fb91c821d2002e61c063fb',
    messagingSenderId: '1043017147554',
    projectId: 'safeti-71954',
    storageBucket: 'safeti-71954.appspot.com',
    iosClientId: '1043017147554-urq8abql5g52u75u7il66qhtpkh9l658.apps.googleusercontent.com',
    iosBundleId: 'com.example.flTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv1AQU4i1d228jyQmPrgJTDYzL514YmOc',
    appId: '1:1043017147554:ios:fb91c821d2002e61c063fb',
    messagingSenderId: '1043017147554',
    projectId: 'safeti-71954',
    storageBucket: 'safeti-71954.appspot.com',
    iosClientId: '1043017147554-urq8abql5g52u75u7il66qhtpkh9l658.apps.googleusercontent.com',
    iosBundleId: 'com.example.flTest',
  );
}
